### ISSUE TITLE
Term rewriting causes vector `+=` operator to fail

### ISSUE THREAD

**Issue by singularperturbation** [unicredit/linear-algebra#2]
I'll open a ticket upstream (in nim-lang/Nim) for this as well, but wanted to see if this could be solved by altering some of the templates in `private/rewrite.nim`:

``` nimrod
import linalg

proc main() =
  const
    vecSize = 3

  var 
    a = zeros(vecSize)
    b = zeros(vecSize)

  let scaleVal = 2.0

  echo "A:"
  a[0] = 3.0; a[1] = 2.0; a[2] = 5.0
  echo a

  echo "B:"
  b[0] = 2.0; b[1] = 3.0; b[2] = 4.0
  echo b

  # Does not compile
  a += b * scaleval

when isMainModule:
  main()
```

gives:

```
addition_with_vector64.nim(32, 5) Error: wrong number of arguments
```

I think that `rewriteLinearCombinationMut` or similar is related, since it _does_ compile with `nim c --patterns:off addition_with_vector64.nim`.  I'm not really familiar with term-rewriting macros' implementation (just re-read section in manual), so I need to take a closer look.

**Comment by singularperturbation** [comment]
Created https://github.com/nim-lang/Nim/issues/4227 upstream for this.

**Comment by andreaferretti** [comment]
I am not sure why this happens. Anyway, I just moved term rewrites into a separate package `linalg/rewrites`, so that this will not break stuff. I will see what is causing this

**Comment by singularperturbation** [comment]
I think it was a compiler error - fixed by https://github.com/nim-lang/Nim/commit/6d76df84546dd90d33a413c0bbd8df75f797767a

Thanks for looking at this.
