### ISSUE TITLE
cannot find default blas on linux

### ISSUE THREAD

**Issue by freevryheid** [unicredit/linear-algebra#7]
[grassy@rockarch newlinalg]$ cat tst.nim
import linalg
echo "hello"
[grassy@rockarch newlinalg]$ nim c tst.nim
Hint: used config file '/etc/nim.cfg' [Conf]
Hint: system [Processing]
Hint: tst [Processing]
Hint: linalg [Processing]
Hint: math [Processing]
Hint: nimblas [Processing]
--USING DEFAULT BLAS--
Hint: random [Processing]
Hint: times [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: sequtils [Processing]
Hint:  [Link]
Hint: operation successful (17456 lines compiled; 0.637 sec total; 37.008MiB; Debug Build) [SuccessX]
[grassy@rockarch newlinalg]$ ./tst
could not import: cblas_sscal
[grassy@rockarch newlinalg]$ locate blas.so
/usr/lib/libblas.so
/usr/lib/libblas.so.3
/usr/lib/libblas.so.3.6.1
/usr/lib/libcblas.so
/usr/lib/julia/libopenblas.so
/usr/lib/julia/libopenblas.so.0

**Comment by mjendrusch** [comment]
I had the very same problem a while ago. Nimblas loads libblas.so by default, but needs the cblas symbols.
Try to run:

```
nm -D libblas.so | grep cblas
```

To see, if they are in libblas.so, if they aren't, that should be the issue. But seeing that you have libcblas.so, you can supply the option -d:atlas for compilation, then libcblas.so should be loaded, which contains the needed symbols.

**Comment by freevryheid** [comment]
Thanks - that was the issue.

**Comment by ghost** [comment]
-d:atlas doesn't work for me.

**Comment by andreaferretti** [comment]
Do you have libatlas.so installed^
